# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'TheStigger'
tagline:             'Solomkin Maxim'
description:         'Keep Calm and Code On'
url:                 https://github.com/TheStigger/
baseurl:             ''
paginate:            5
pages_list:
    About: '/about'
    Archive: '/archive'
    Feed: '/atom.xml'

# About/contact
author:
  name:              Maxim Solomkin
  url:               https://twitter.com/solomkinmv
  email:             solomkinmv@gmail.com

# Custom vars
version:             0.0.1
